"""add foreign keys and relationships

Revision ID: 7c00a51f4bab
Revises: d98256fde8b3
Create Date: 2026-08-11 11:34:22.827767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c00a51f4bab'
down_revision = 'd98256fde8b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'regions', ['region_id'], ['id'])
        batch_op.create_foreign_key(None, 'ministry', ['ministry_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
