"""add to_admin column to message

Revision ID: 874406a082e4
Revises: 55f6eb1ea05d
Create Date: 2026-08-11 09:21:55.263062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874406a082e4'
down_revision = '55f6eb1ea05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('to_admin')

    # ### end Alembic commands ###
