"""add is_read and read_time column to message

Revision ID: 99aa32117b55
Revises: 874406a082e4
Create Date: 2026-08-11 09:27:38.453321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99aa32117b55'
down_revision = '874406a082e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('read_time')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
