"""init with enplans

Revision ID: a48b178053c9
Revises: 925e7a724c74
Create Date: 2026-08-17 09:39:18.101775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a48b178053c9'
down_revision = '925e7a724c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_erespondentn', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_enplans', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_auditor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_approver', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_reader', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('post', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('begin_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_password_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_password_expires', sa.DateTime(), nullable=True))
        batch_op.alter_column('last_active',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_active',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('reset_password_expires')
        batch_op.drop_column('reset_password_token')
        batch_op.drop_column('begin_time')
        batch_op.drop_column('post')
        batch_op.drop_column('is_reader')
        batch_op.drop_column('is_approver')
        batch_op.drop_column('is_auditor')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('is_enplans')
        batch_op.drop_column('is_erespondentn')

    # ### end Alembic commands ###
