"""add region_id and ministry_id columns

Revision ID: d37a2b12f101
Revises: 99aa32117b55
Create Date: 2026-08-11 11:31:46.759424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37a2b12f101'
down_revision = '99aa32117b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ministry_id', sa.Integer(), nullable=True))
        batch_op.drop_column('ministry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ministry', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('ministry_id')
        batch_op.drop_column('region_id')

    # ### end Alembic commands ###
