"""fio by words

Revision ID: d3fb2675843d
Revises: a48b178053c9
Create Date: 2026-08-17 10:20:20.331852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3fb2675843d'
down_revision = 'a48b178053c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PlanTickets')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('patronymic_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('patronymic_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    op.create_table('PlanTickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('begin_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('luck', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name='PlanTickets_plan_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='PlanTickets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='PlanTickets_pkey')
    )
    # ### end Alembic commands ###
