"""add boolean flags to organization

Revision ID: d98256fde8b3
Revises: d37a2b12f101
Create Date: 2026-08-11 11:33:22.473440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98256fde8b3'
down_revision = 'd37a2b12f101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_regular', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_coordinator', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_approver', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_region_management', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('is_region_management')
        batch_op.drop_column('is_approver')
        batch_op.drop_column('is_coordinator')
        batch_op.drop_column('is_regular')

    # ### end Alembic commands ###
